env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 30s
  user: "artem"
  password: "123"
postgres:
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  user: "postgres"
  password: "password"
  sslmode: "disable"